/**
 * Shamrock token compiler.
 *
 * Sources are DTCG-format JSON (design-tokens community group format — the same
 * shape Figma Variables sync tooling speaks). This script resolves {references}
 * and emits:
 *
 *   dist/css/core.css          :root — the full colorless semantic system
 *   dist/css/theme-<name>.css  [data-theme="<name>"] — accent/font overrides only
 *   dist/js/tokens.js|d.ts     typed flat token map + css var names for JS consumers
 *
 * Brand color primitives (green/violet/…) are compiled INTO theme files via
 * references but never emitted as vars themselves — core stays colorless.
 */
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "src");

const PREFIX = "sh";

/** Deep-merge token trees (plain objects). */
function merge(target, source) {
  for (const [key, value] of Object.entries(source)) {
    if (value && typeof value === "object" && !Array.isArray(value) && target[key] && typeof target[key] === "object") {
      merge(target[key], value);
    } else {
      target[key] = value;
    }
  }
  return target;
}

function loadDir(dir) {
  const tree = {};
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json")).sort()) {
    merge(tree, JSON.parse(readFileSync(join(dir, file), "utf8")));
  }
  return tree;
}

/** Flatten a DTCG tree into [path[], token] pairs. */
function flatten(node, path = [], out = []) {
  if (node && typeof node === "object") {
    if ("$value" in node) {
      out.push([path, node]);
      return out;
    }
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith("$")) continue;
      flatten(child, [...path, key], out);
    }
  }
  return out;
}

function getByPath(tree, dotPath) {
  let node = tree;
  for (const part of dotPath.split(".")) {
    node = node?.[part];
    if (node === undefined) return undefined;
  }
  return node;
}

/** Resolve {dot.path} references against a context tree. */
function resolve(value, context, seen = new Set()) {
  return String(value).replace(/\{([^}]+)\}/g, (_, refPath) => {
    if (seen.has(refPath)) throw new Error(`Circular token reference: ${refPath}`);
    const target = getByPath(context, refPath);
    if (!target || typeof target !== "object" || !("$value" in target)) {
      throw new Error(`Unresolved token reference: {${refPath}}`);
    }
    return resolve(target.$value, context, new Set([...seen, refPath]));
  });
}

const varName = (path) => `--${PREFIX}-${path.join("-")}`;

function toCssBlock(selector, entries) {
  const lines = entries.map(([path, value]) => `  ${varName(path)}: ${value};`);
  return `${selector} {\n${lines.join("\n")}\n}\n`;
}

// ---- load tiers -------------------------------------------------------------
const primitives = loadDir(join(src, "primitive"));
const semantic = loadDir(join(src, "semantic"));
const core = merge(structuredClone(primitives), semantic);

// Brand color families never appear as CSS vars: core emits primitives
// (space/font/shadow/…) EXCEPT color.*, plus every semantic token resolved.
const BRAND_ONLY = new Set(["green", "violet"]);
const coreEntries = flatten(core)
  .filter(([path]) => !(path[0] === "color" && BRAND_ONLY.has(path[1])))
  .map(([path, token]) => [path, resolve(token.$value, core)]);

// ---- themes -----------------------------------------------------------------
const themeDir = join(src, "themes");
const themes = {};
for (const file of readdirSync(themeDir).filter((f) => f.endsWith(".json")).sort()) {
  const name = basename(file, ".json");
  const overrides = JSON.parse(readFileSync(join(themeDir, file), "utf8"));
  delete overrides.$description;
  const context = merge(structuredClone(core), overrides);
  themes[name] = flatten(overrides).map(([path, token]) => [path, resolve(token.$value, context)]);
}

// ---- emit -------------------------------------------------------------------
const banner = `/* Generated by @shamrock/tokens — do not edit. Sources: packages/tokens/src */\n`;
mkdirSync(join(root, "dist/css"), { recursive: true });
mkdirSync(join(root, "dist/js"), { recursive: true });

writeFileSync(join(root, "dist/css/core.css"), banner + toCssBlock(":root", coreEntries));

for (const [name, entries] of Object.entries(themes)) {
  writeFileSync(
    join(root, `dist/css/theme-${name}.css`),
    banner + toCssBlock(`[data-theme="${name}"]`, entries),
  );
}

const jsTokens = Object.fromEntries(coreEntries.map(([path, value]) => [path.join("."), value]));
const jsVars = Object.fromEntries(coreEntries.map(([path]) => [path.join("."), `var(${varName(path)})`]));
const themeNames = Object.keys(themes);

writeFileSync(
  join(root, "dist/js/tokens.js"),
  banner +
    `export const tokens = ${JSON.stringify(jsTokens, null, 2)};\n\n` +
    `export const cssVar = ${JSON.stringify(jsVars, null, 2)};\n\n` +
    `export const themeNames = ${JSON.stringify(themeNames)};\n`,
);

writeFileSync(
  join(root, "dist/js/tokens.d.ts"),
  banner +
    `/** Resolved core (colorless) token values, keyed by dot path (e.g. "color.accent.base"). */\n` +
    `export declare const tokens: Record<string, string>;\n` +
    `/** var(--sh-*) expressions per token, for inline styles / chart configs. */\n` +
    `export declare const cssVar: Record<string, string>;\n` +
    `export declare const themeNames: ${themeNames.map((n) => JSON.stringify(n)).join(" | ")}[];\n`,
);

console.log(
  `tokens: ${coreEntries.length} core vars, themes: ${themeNames
    .map((n) => `${n} (${themes[n].length})`)
    .join(", ")}`,
);
