/**
 * Icon pipeline: svg/*.svg → src/generated/icons.ts
 *
 * Contract for source SVGs (CI-enforced here):
 *  - filename kebab-case
 *  - viewBox="0 0 24 24"
 *  - no hardcoded fill/stroke colors — currentColor only
 *
 * With --check, validates without writing (used as the package test).
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const svgDir = join(root, "svg");
const checkOnly = process.argv.includes("--check");

const files = readdirSync(svgDir).filter((f) => f.endsWith(".svg")).sort();
const errors = [];
const icons = {};

for (const file of files) {
  const name = basename(file, ".svg");
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(name)) errors.push(`${file}: filename must be kebab-case`);
  const raw = readFileSync(join(svgDir, file), "utf8");
  if (!raw.includes('viewBox="0 0 24 24"')) errors.push(`${file}: viewBox must be "0 0 24 24"`);
  const colorAttrs = raw.match(/(?:fill|stroke)="(?!currentColor|none)[^"]+"/g);
  if (colorAttrs) errors.push(`${file}: hardcoded colors ${colorAttrs.join(", ")} — use currentColor`);
  const inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>[\s\S]*$/, "").trim();
  if (!inner) errors.push(`${file}: empty svg body`);
  icons[name] = inner;
}

if (errors.length > 0) {
  for (const e of errors) console.error(`✗ ${e}`);
  process.exit(1);
}

console.log(`✓ ${files.length} icons valid`);
if (checkOnly) process.exit(0);

const out =
  `/* Generated by scripts/build-icons.mjs — do not edit. Sources: packages/icons/svg */\n` +
  `export const ICON_PATHS = ${JSON.stringify(icons, null, 2)} as const;\n\n` +
  `export type IconName = keyof typeof ICON_PATHS;\n` +
  `export const ICON_NAMES = Object.keys(ICON_PATHS) as IconName[];\n`;

mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(join(root, "src/generated/icons.ts"), out);
